"""
Dataclasses for the safety app.

Provides data transfer objects for permission operations.
Requirements: 10.1-10.7
"""

from dataclasses import dataclass
from typing import Optional, List
from datetime import datetime


@dataclass
class PermissionCheckResult:
    """
    Result of a permission check.
    
    Attributes:
        allowed: Whether the action is allowed
        needs_approval: Whether per-action approval is needed
        reason: Explanation for the result
    """
    
    allowed: bool
    needs_approval: bool
    reason: Optional[str] = None
    
    @classmethod
    def denied(cls, reason: str = "Permission not granted") -> 'PermissionCheckResult':
        """Create a denied result."""
        return cls(allowed=False, needs_approval=False, reason=reason)
    
    @classmethod
    def allowed_with_approval(cls, reason: str = "Requires approval") -> 'PermissionCheckResult':
        """Create an allowed result that requires approval."""
        return cls(allowed=True, needs_approval=True, reason=reason)
    
    @classmethod
    def allowed_without_approval(cls) -> 'PermissionCheckResult':
        """Create an allowed result that doesn't require approval."""
        return cls(allowed=True, needs_approval=False, reason=None)


@dataclass
class PermissionScopeData:
    """
    Data transfer object for permission scope information.
    
    Attributes:
        integration: The integration name
        action_type: The action type
        is_granted: Whether permission is granted
        requires_approval: Whether per-action approval is needed
        is_high_risk: Whether this is a high-risk action
    """
    
    integration: str
    action_type: str
    is_granted: bool
    requires_approval: bool
    is_high_risk: bool
    
    @classmethod
    def from_model(cls, permission_scope) -> 'PermissionScopeData':
        """Create from a PermissionScope model instance."""
        return cls(
            integration=permission_scope.integration,
            action_type=permission_scope.action_type,
            is_granted=permission_scope.is_granted,
            requires_approval=permission_scope.requires_approval,
            is_high_risk=permission_scope.is_high_risk,
        )


@dataclass
class PermissionUpdateRequest:
    """
    Request to update a permission scope.
    
    Attributes:
        integration: The integration name
        action_type: The action type
        is_granted: New granted status (optional)
        requires_approval: New approval requirement (optional)
        reason: Reason for the change
    """
    
    integration: str
    action_type: str
    is_granted: Optional[bool] = None
    requires_approval: Optional[bool] = None
    reason: str = ""


@dataclass
class AuditEntryData:
    """
    Data transfer object for audit entry information.
    
    Requirements: 11.1, 11.5
    
    Attributes:
        id: Unique identifier
        user_id: The user who owns this audit entry
        twin_id: The Twin that performed the action (optional)
        timestamp: When the action occurred
        action_type: The type of action performed
        target_integration: The integration the action was performed on
        input_data: Input data for the action
        outcome: The outcome of the action
        cognitive_blend: Cognitive blend value used
        reasoning_chain: The reasoning chain for the decision
        is_twin_generated: Whether this action was generated by the Twin
        checksum: SHA-256 checksum for tamper detection
    """
    
    id: str
    user_id: str
    twin_id: Optional[str]
    timestamp: datetime
    action_type: str
    target_integration: Optional[str]
    input_data: dict
    outcome: str
    cognitive_blend: Optional[int]
    reasoning_chain: str
    is_twin_generated: bool
    checksum: str
    
    @classmethod
    def from_model(cls, audit_entry) -> 'AuditEntryData':
        """Create from an AuditEntry model instance."""
        return cls(
            id=str(audit_entry.id),
            user_id=str(audit_entry.user_id),
            twin_id=str(audit_entry.twin_id) if audit_entry.twin_id else None,
            timestamp=audit_entry.timestamp,
            action_type=audit_entry.action_type,
            target_integration=audit_entry.target_integration,
            input_data=audit_entry.input_data,
            outcome=audit_entry.outcome,
            cognitive_blend=audit_entry.cognitive_blend,
            reasoning_chain=audit_entry.reasoning_chain,
            is_twin_generated=audit_entry.is_twin_generated,
            checksum=audit_entry.checksum,
        )


@dataclass
class AuditLogRequest:
    """
    Request to log an audit entry.
    
    Requirements: 11.1
    
    Attributes:
        action_type: The type of action performed
        target_integration: The integration the action was performed on
        input_data: Input data for the action
        outcome: The outcome of the action
        cognitive_blend: Cognitive blend value used
        reasoning_chain: The reasoning chain for the decision
        is_twin_generated: Whether this action was generated by the Twin
        twin_id: The Twin that performed the action (optional)
    """
    
    action_type: str
    outcome: str
    target_integration: Optional[str] = None
    input_data: Optional[dict] = None
    cognitive_blend: Optional[int] = None
    reasoning_chain: str = ""
    is_twin_generated: bool = True
    twin_id: Optional[str] = None


@dataclass
class AuditFilterCriteria:
    """
    Filter criteria for querying audit history.
    
    Requirements: 11.3
    
    Attributes:
        start_date: Filter entries from this date
        end_date: Filter entries until this date
        action_type: Filter by action type
        target_integration: Filter by target integration
        outcome: Filter by outcome
        twin_id: Filter by Twin ID
    """
    
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    action_type: Optional[str] = None
    target_integration: Optional[str] = None
    outcome: Optional[str] = None
    twin_id: Optional[str] = None


@dataclass
class ReversibleActionData:
    """
    Data for a reversible action that can be undone.
    
    Requirements: 12.6
    
    Attributes:
        action_id: Unique identifier for the action
        user_id: The user who owns this action
        action_type: The type of action performed
        target_integration: The integration the action was performed on
        original_state: The state before the action (for rollback)
        new_state: The state after the action
        undo_deadline: Deadline for undoing the action
        is_undone: Whether the action has been undone
        created_at: When the action was performed
    """
    
    action_id: str
    user_id: str
    action_type: str
    target_integration: Optional[str]
    original_state: dict
    new_state: dict
    undo_deadline: datetime
    is_undone: bool
    created_at: datetime
    
    @classmethod
    def from_model(cls, reversible_action) -> 'ReversibleActionData':
        """Create from a ReversibleAction model instance."""
        return cls(
            action_id=str(reversible_action.id),
            user_id=str(reversible_action.user_id),
            action_type=reversible_action.action_type,
            target_integration=reversible_action.target_integration,
            original_state=reversible_action.original_state,
            new_state=reversible_action.new_state,
            undo_deadline=reversible_action.undo_deadline,
            is_undone=reversible_action.is_undone,
            created_at=reversible_action.created_at,
        )


@dataclass
class KillSwitchStatus:
    """
    Status of the kill switch for a user.
    
    Requirements: 12.1, 12.2, 12.3
    
    Attributes:
        is_active: Whether the kill switch is currently active
        activated_at: When the kill switch was activated (if active)
        activated_by: Who activated the kill switch (user or system)
        reason: Reason for activation
    """
    
    is_active: bool
    activated_at: Optional[datetime] = None
    activated_by: Optional[str] = None
    reason: Optional[str] = None
