"""
Workflow Service.

Enhanced workflow management with Twin modification support.
Requirements: 7.1-7.9, 8.1-8.7
"""

import logging
from uuid import UUID
from typing import Optional

from django.core.exceptions import ValidationError
from django.db import transaction
from django.utils import timezone

from apps.automation.models import (
    Workflow,
    WorkflowChangeHistory,
    Integration,
    IntegrationTypeModel,
)

logger = logging.getLogger(__name__)


class WorkflowService:
    """Service for workflow management."""
    
    @staticmethod
    def create_workflow(
        user,
        name: str,
        trigger_config: dict,
        steps: list[dict],
        is_twin_generated: bool = False
    ):
        """
        Create a new workflow with validation.
        
        Validates:
        - Workflow has at least one step
        - All integration_type_id references are installed by user
        - Sets is_custom flag appropriately
        
        Requirements: 7.7-7.8
        
        Args:
            user: Current user
            name: Workflow name
            trigger_config: Trigger configuration
            steps: List of workflow steps
            is_twin_generated: Whether generated by Twin
            
        Returns:
            Workflow: Created workflow
            
        Raises:
            ValidationError: If validation fails
        """
        # Validate at least one step
        if not steps or len(steps) == 0:
            raise ValidationError('Workflow must have at least one step')
        
        # Validate all integration_type_id references are installed
        is_valid, missing_integrations = WorkflowService.validate_workflow_integrations(
            user, steps
        )
        if not is_valid:
            raise ValidationError(
                f'Missing required integrations: {", ".join(missing_integrations)}'
            )
        
        # Create workflow
        workflow = Workflow.objects.create(
            user=user,
            name=name,
            trigger_config=trigger_config,
            steps=steps,
            is_custom=True,  # User-created workflows are always custom
            automation_template=None,  # No template for custom workflows
            last_modified_by_twin=is_twin_generated,
            twin_modification_count=1 if is_twin_generated else 0,
            is_active=True,
        )
        
        logger.info(
            f'Created workflow {workflow.id} for user {user.id}: {name}'
        )
        
        return workflow
    
    @staticmethod
    @transaction.atomic
    def update_workflow(
        workflow_id: UUID,
        user,
        updates: dict,
        modified_by_twin: bool = False,
        cognitive_blend: Optional[int] = None,
        permission_flag: bool = False
    ):
        """
        Update workflow with Twin safety checks.
        
        Implements Twin safety controls:
        - Requires permission_flag=True for Twin modifications
        - Fetches cognitive_blend from user's Twin profile
        - Requires confirmation if cognitive_blend > 80%
        - Creates WorkflowChangeHistory record
        - Logs modification in audit log
        - Validates integration availability
        
        Requirements: 8.1-8.7
        
        Args:
            workflow_id: ID of workflow to update
            user: Current user
            updates: Fields to update
            modified_by_twin: Whether modified by Twin
            cognitive_blend: Optional override for cognitive blend value (if None, fetches from Twin)
            permission_flag: Whether Twin has permission
            
        Returns:
            Workflow: Updated workflow
            
        Raises:
            ValidationError: If validation fails
            PermissionError: If Twin lacks permission
        """
        # Get workflow
        try:
            workflow = Workflow.objects.select_for_update().get(
                id=workflow_id,
                user=user
            )
        except Workflow.DoesNotExist:
            raise ValidationError(f'Workflow {workflow_id} not found')
        
        # Twin safety checks
        if modified_by_twin:
            # Requirement 8.1: Check permission_flag for Twin modifications
            if not permission_flag:
                logger.warning(
                    f'Twin attempted workflow modification without permission: '
                    f'workflow={workflow_id}, user={user.id}'
                )
                raise PermissionError(
                    'Twin modifications require permission_flag=True'
                )
            
            # Requirement 8.2: Fetch cognitive_blend from user's Twin profile
            if cognitive_blend is None:
                from apps.twin.models import Twin
                try:
                    twin = Twin.objects.get(user=user, is_active=True)
                    cognitive_blend = twin.cognitive_blend
                    logger.info(
                        f'Fetched cognitive_blend={cognitive_blend} from Twin '
                        f'for user {user.id}'
                    )
                except Twin.DoesNotExist:
                    logger.warning(
                        f'No active Twin found for user {user.id}, '
                        f'using default cognitive_blend=50'
                    )
                    cognitive_blend = 50
            
            # Requirement 8.3: Require confirmation if cognitive_blend > 80%
            if cognitive_blend > 80:
                logger.info(
                    f'High cognitive blend detected ({cognitive_blend}%) - '
                    f'confirmation required for workflow {workflow_id}'
                )
                # Note: Actual confirmation handling should be done at API layer
                # This service method assumes confirmation was already obtained
                # if it's being called with high blend
        
        # Validate integration availability if steps are being updated
        if 'steps' in updates:
            is_valid, missing_integrations = WorkflowService.validate_workflow_integrations(
                user, updates['steps']
            )
            if not is_valid:
                raise ValidationError(
                    f'Missing required integrations: {", ".join(missing_integrations)}'
                )
        
        # Track changes for history
        changes_made = {}
        for field, new_value in updates.items():
            old_value = getattr(workflow, field, None)
            if old_value != new_value:
                changes_made[field] = {
                    'before': old_value,
                    'after': new_value
                }
        
        # Update workflow fields
        for field, value in updates.items():
            setattr(workflow, field, value)
        
        # Update Twin tracking
        if modified_by_twin:
            workflow.last_modified_by_twin = True
            workflow.twin_modification_count += 1
        else:
            workflow.last_modified_by_twin = False
        
        workflow.save()
        
        # Requirement 8.7: Create WorkflowChangeHistory record
        # Requirement 8.2: Store cognitive_blend_value in history
        WorkflowChangeHistory.objects.create(
            workflow=workflow,
            user=user,
            modified_by_twin=modified_by_twin,
            cognitive_blend_value=cognitive_blend if modified_by_twin else None,
            changes_made=changes_made,
            reasoning=updates.get('_reasoning', ''),  # Optional reasoning field
            permission_flag=permission_flag,
            required_confirmation=modified_by_twin and cognitive_blend is not None and cognitive_blend > 80,
        )
        
        # Requirement 8.2: Log modification in audit log
        logger.info(
            f'Workflow updated: id={workflow_id}, user={user.id}, '
            f'by_twin={modified_by_twin}, blend={cognitive_blend}, '
            f'changes={list(changes_made.keys())}'
        )
        
        return workflow
    
    @staticmethod
    def validate_workflow_integrations(
        user,
        steps: list[dict]
    ) -> tuple[bool, list[str]]:
        """
        Validate all referenced integrations are installed.
        
        Checks that all integration_type_id values in workflow steps
        correspond to integrations that the user has installed.
        
        Requirements: 7.6, 8.5
        
        Args:
            user: Current user
            steps: List of workflow steps
            
        Returns:
            tuple: (is_valid, list of missing integration type IDs)
        """
        if not steps:
            return True, []
        
        # Extract all integration_type_id values from steps
        required_integration_type_ids = set()
        for step in steps:
            if 'integration_type_id' in step:
                integration_type_id = step['integration_type_id']
                # Handle both UUID and string representations
                required_integration_type_ids.add(str(integration_type_id))
        
        if not required_integration_type_ids:
            return True, []
        
        # Get user's installed integration type IDs
        installed_integration_type_ids = set(
            Integration.objects.filter(
                user=user,
                is_active=True
            ).values_list('integration_type_id', flat=True)
        )
        
        # Convert to strings for comparison
        installed_integration_type_ids = {
            str(id) for id in installed_integration_type_ids
        }
        
        # Find missing integrations
        missing_integration_type_ids = (
            required_integration_type_ids - installed_integration_type_ids
        )
        
        is_valid = len(missing_integration_type_ids) == 0
        
        if not is_valid:
            logger.warning(
                f'Workflow validation failed for user {user.id}: '
                f'missing integrations {missing_integration_type_ids}'
            )
        
        return is_valid, list(missing_integration_type_ids)
    
    @staticmethod
    def disable_workflows_for_integration(
        user,
        integration_type_id: UUID
    ) -> int:
        """
        Disable workflows that depend on an integration.
        
        Finds all workflows that use the specified integration type
        in their steps and sets is_active=False for each.
        
        Requirements: 5.5
        
        Args:
            user: Current user
            integration_type_id: ID of integration type
            
        Returns:
            int: Count of disabled workflows
        """
        # Convert UUID to string for JSON comparison
        integration_type_id_str = str(integration_type_id)
        
        # Get all active workflows for the user
        workflows = Workflow.objects.filter(
            user=user,
            is_active=True
        )
        
        disabled_count = 0
        
        for workflow in workflows:
            # Check if workflow uses this integration type
            steps = workflow.get_steps_list()
            uses_integration = False
            
            for step in steps:
                step_integration_id = step.get('integration_type_id')
                if step_integration_id and str(step_integration_id) == integration_type_id_str:
                    uses_integration = True
                    break
            
            if uses_integration:
                workflow.is_active = False
                workflow.save(update_fields=['is_active', 'updated_at'])
                disabled_count += 1
                
                logger.info(
                    f'Disabled workflow {workflow.id} ({workflow.name}) '
                    f'due to integration type {integration_type_id} removal'
                )
        
        if disabled_count > 0:
            logger.info(
                f'Disabled {disabled_count} workflows for user {user.id} '
                f'after removing integration type {integration_type_id}'
            )
        
        return disabled_count
